"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AllocateUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    ROOM_ID_FIELD_NUMBER: builtins.int
    CRYPTO_KEY_FIELD_NUMBER: builtins.int
    CRYPTO_SALT_FIELD_NUMBER: builtins.int
    uid: builtins.str
    token: builtins.str
    room_id: builtins.int
    crypto_key: builtins.bytes
    crypto_salt: builtins.bytes
    def __init__(
        self,
        *,
        uid: builtins.str = ...,
        token: builtins.str = ...,
        room_id: builtins.int = ...,
        crypto_key: builtins.bytes = ...,
        crypto_salt: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["crypto_key", b"crypto_key", "crypto_salt", b"crypto_salt", "room_id", b"room_id", "token", b"token", "uid", b"uid"]) -> None: ...

global___AllocateUserRequest = AllocateUserRequest

@typing.final
class RemoveUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    uid: builtins.str
    def __init__(
        self,
        *,
        uid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["uid", b"uid"]) -> None: ...

global___RemoveUserRequest = RemoveUserRequest
