# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import server_pb2 as server__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SyncServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.allocate_user = channel.unary_unary(
                '/MovanServer.SyncServer/allocate_user',
                request_serializer=server__pb2.AllocateUserRequest.SerializeToString,
                response_deserializer=common__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.remove_user = channel.unary_unary(
                '/MovanServer.SyncServer/remove_user',
                request_serializer=server__pb2.RemoveUserRequest.SerializeToString,
                response_deserializer=common__pb2.BoolResponse.FromString,
                _registered_method=True)


class SyncServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def allocate_user(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def remove_user(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SyncServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'allocate_user': grpc.unary_unary_rpc_method_handler(
                    servicer.allocate_user,
                    request_deserializer=server__pb2.AllocateUserRequest.FromString,
                    response_serializer=common__pb2.BoolResponse.SerializeToString,
            ),
            'remove_user': grpc.unary_unary_rpc_method_handler(
                    servicer.remove_user,
                    request_deserializer=server__pb2.RemoveUserRequest.FromString,
                    response_serializer=common__pb2.BoolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MovanServer.SyncServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MovanServer.SyncServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SyncServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def allocate_user(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MovanServer.SyncServer/allocate_user',
            server__pb2.AllocateUserRequest.SerializeToString,
            common__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def remove_user(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MovanServer.SyncServer/remove_user',
            server__pb2.RemoveUserRequest.SerializeToString,
            common__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
