[Network]
account_server_host = "0.0.0.0"
account_server_port = 2027


[SyncServer]
urls = ["127.0.0.1:50051"] # 对应下标为对应SyncServer编号


[Log]
sink="account_server.log"
rotation="500 MB"  # 当日志文件达到500MB时轮转
retention="10 days"  # 保留10天的日志
compression="zip"  # 使用zip压缩轮转后的日志
enqueue=true  # 启用异步写入
backtrace=true  # 记录异常的完整堆栈跟踪
diagnose=true  # 允许诊断异常
level="INFO"  # 设置日志级别

[DataBase]
url="mysql+pymysql://root:8868384asdf@localhost/movan_server" # 数据库url和密码请自己替换 这里只是示例


[Security]
jwt_secret = "your-secret-key" # JWT 密钥
excluded_methods = [
    "/MovanClient.AccountServer/account_register",
    "/MovanClient.AccountServer/account_login",
]  # 不需要认证的方法列表