# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in client_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccountServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.account_register = channel.unary_unary(
                '/MovanClient.AccountServer/account_register',
                request_serializer=common__pb2.AccountRegisterRequest.SerializeToString,
                response_deserializer=common__pb2.BoolResponse.FromString,
                _registered_method=True)
        self.account_login = channel.unary_unary(
                '/MovanClient.AccountServer/account_login',
                request_serializer=common__pb2.AccountLoginRequest.SerializeToString,
                response_deserializer=common__pb2.AccountLoginResponse.FromString,
                _registered_method=True)


class AccountServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def account_register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def account_login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'account_register': grpc.unary_unary_rpc_method_handler(
                    servicer.account_register,
                    request_deserializer=common__pb2.AccountRegisterRequest.FromString,
                    response_serializer=common__pb2.BoolResponse.SerializeToString,
            ),
            'account_login': grpc.unary_unary_rpc_method_handler(
                    servicer.account_login,
                    request_deserializer=common__pb2.AccountLoginRequest.FromString,
                    response_serializer=common__pb2.AccountLoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MovanClient.AccountServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MovanClient.AccountServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccountServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def account_register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MovanClient.AccountServer/account_register',
            common__pb2.AccountRegisterRequest.SerializeToString,
            common__pb2.BoolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def account_login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MovanClient.AccountServer/account_login',
            common__pb2.AccountLoginRequest.SerializeToString,
            common__pb2.AccountLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
