# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: encrypted_message.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'encrypted_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x65ncrypted_message.proto\"U\n\x10\x45ncryptedMessage\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x16\n\x0e\x65ncrypted_data\x18\x02 \x01(\x0c\x12\x1c\n\x14\x65ncrypted_extra_data\x18\x03 \x01(\x0c\"<\n\tExtraData\x12\r\n\x05proto\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\r\n\x05token\x18\x03 \x01(\t\"M\n\x10\x44\x65\x63ryptedMessage\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x1e\n\nextra_data\x18\x03 \x01(\x0b\x32\n.ExtraDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'encrypted_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCRYPTEDMESSAGE']._serialized_start=27
  _globals['_ENCRYPTEDMESSAGE']._serialized_end=112
  _globals['_EXTRADATA']._serialized_start=114
  _globals['_EXTRADATA']._serialized_end=174
  _globals['_DECRYPTEDMESSAGE']._serialized_start=176
  _globals['_DECRYPTEDMESSAGE']._serialized_end=253
# @@protoc_insertion_point(module_scope)
