[KCP] # 已配置为极速模式
no_delay = true
update_interval = 10
resend_count = 2
no_congestion_control = true

[Network]
host = "127.0.0.1"
port = 2025


[Server]
num_of_rooms = 4


[Log]
sink="sync_server.log"
rotation="500 MB"  # 当日志文件达到500MB时轮转
retention="10 days"  # 保留10天的日志
compression="zip"  # 使用zip压缩轮转后的日志
enqueue=true  # 启用异步写入
backtrace=true  # 记录异常的完整堆栈跟踪
diagnose=true  # 允许诊断异常
level="INFO"  # 设置日志级别

[SyncCore]
update_interval = 20 # 单位为毫秒